projects:
  service:
    schemaPath: src/service/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/service/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      codegen:
        - generator: prisma-binding
          language: javascript
          output:
            binding: service/generated/prisma.js
