os: linux
dist: trusty
language: node_js
sudo: required
node_js:
  - "8"
  - "10"
cache:
  directories:
    - "node_modules"
services:
  - docker
env:
  global:
    - PRISMA_ENDPOINT=http://prisma:4466
    - DOCKER_COMPOSE_VERSION=1.22.0
install:
  - yarn install
script:
  - yarn run ci:remote
