version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - "mysql"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma-service:
    build: "."
    ports:
      - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
      PRISMA_CLUSTER: local
      PRISMA_SECRET: ${PRISMA_SECRET}
    restart: always
    depends_on:
      - "prisma"
      - "mysql"

volumes:
  mysql: ~

networks:
  default:
    name: prisma-starter-net
